auth/urls.py
from django.urls import path

from auth.views import LoginView, ProfileView, SignUpView, PasswordChangeView, EmailChangeView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView

from menu.views import MenuEditView

app_name = 'auth'
urlpatterns = [
    path('',
         LoginView.as_view(),
         name='login'),

    path('logout/',
         LogoutView.as_view(template_name="internal/auth/logged_out.html"),
         name='logout'),

    path('password_change/',
         PasswordChangeView.as_view(),
         name="password_change"),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name="internal/auth/password_change_done.html"),
         name="password_change_done"),


    path('signup/', SignUpView.as_view(), name='sign_up'),
    path('management/', ProfileView.as_view(), name='logged_in'),


    path('edit_menu/', MenuEditView.as_view(), name='edit_menu'),
    path('change_email', EmailChangeView.as_view(), name='change_email')
]

reservation/urls.py
from django.urls import path

from reservation.views import ReservationView, ajax_reservation, ajax_get_available_tables

app_name = 'reservation'
urlpatterns = [
    path('', ReservationView.as_view(), name='home'),
    path('reserve', ajax_reservation, name="ajax_reservation"),
    path('get-table', ajax_get_available_tables, name='ajax_get_available_tables')
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('menu/', include("menu.urls")),
    path('reservierung/', include("reservation.urls")),
    path('konto/', include("auth.urls"))
]

reservation/models.py
from django.db import models

import pandas as pd


class Table(models.Model):
    table_name = models.CharField(max_length=5, unique=True)
    seat_count = models.PositiveIntegerField(default=2)

    def __str__(self):
        return f"T{self.table_name} ({self.seat_count}x)"

    def is_free_at(self, timestamp:pd.Timestamp)->bool:
        """
        Check if this table is free at this timestamp
        :param timestamp:
        :return:
        """

        reservation_tables = ReservationTable.objects.filter(table=self, reservation__time_reserved__day=timestamp.day)
        for reservation_table in reservation_tables:
            reservation = reservation_table.reservation

            time_start = reservation.time_start or reservation.time_reserved # true start time or expected (if not come yet)
            time_end = reservation.time_end or (reservation.time_reserved + pd.Timedelta(hours=2))

            is_inbetween = time_start <= timestamp < time_end # should use <= at the 2nd position?

            if is_inbetween:
                return False

        return True


    @staticmethod
    def get_free_at(timestamp:pd.Timestamp)->list:
        """
        Get all free table at this timestamp
        :param timestamp:
        :return:
        """

        tables = Table.objects.all()
        unassigned = []

        for table in tables:
            if table.is_free_at(timestamp):
                unassigned.append(table)

        return unassigned


class Reservation(models.Model):
    customer_name = models.CharField(max_length=20)
    customer_phone = models.CharField(max_length=15, default="Leer", null=True)


    time_reserved = models.DateTimeField() # time_start == null => reserved
    time_start = models.DateTimeField(null=True) # time end == null && time_start != null => occupied
    time_end = models.DateTimeField(null=True) # time end < current => free

    seat_count = models.PositiveSmallIntegerField()

    def __str__(self):
        assigned_tables = self.tables

        date_str = f"{self.time_reserved.strftime('%Y-%m-%d %H:%M')}"
        date_today = pd.Timestamp.now().strftime('%Y-%m-%d')
        if date_today in date_str:
            date_str = date_str.replace(date_today, 'Heute')

        if self.time_end:
            date_str += self.time_end.strftime(" - %H:%M")

        date_str += f" - {self.customer_name}"

        if assigned_tables:
            tables = ""
            for table in assigned_tables:
                tables += f"T{table.table_name}, "

            date_str += f" ({tables[:-2]})" # remove last 2 char (, and space)
        else:
            date_str += f" ({self.seat_count}x)"


        return date_str


    def get_reserved_time_str(self)->str:
        date_reserved = self.time_reserved.date()
        date_today = pd.Timestamp.now().date()

        if date_today == date_reserved:
            return f'heute um {self.time_reserved.strftime("%H:%M")}'
        else:
            return self.time_reserved.strftime("%d.%m um %H:%M")


    @property
    def tables(self)->list[Table]:
        try:
            return ReservationTable.get_tables(reservation=self)
        except ReservationTable.DoesNotExist:
            return []


    @staticmethod
    def get_unassigned(): # reserved but not assigned to a table yet
        today = pd.Timestamp.now().floor('D')
        reservations_today = Reservation.objects.filter(time_reserved__gte=today)
        unassigned = []

        for reservation in reservations_today:
            started = reservation.time_start
            assigned = reservation.tables

            if (not assigned) and (not started):
                unassigned.append(reservation)

        return unassigned


    @staticmethod
    def get_waiting(): # assigned to a table, but hasn't come yet
        today = pd.Timestamp.now().floor('D')
        reservations_today = Reservation.objects.filter(time_reserved__gte=today)

        waiting = []
        for reservation in reservations_today:
            started = reservation.time_start
            assigned = reservation.tables

            if assigned and (not started):
                waiting.append(reservation)

        return waiting


    @staticmethod
    def get_on_going(): # came, but hasn't finished yet
        today = pd.Timestamp.now().floor('D')
        reservations_today = Reservation.objects.filter(time_reserved__gte=today)

        return reservations_today.filter(time_start__isnull=False, time_end__isnull=True)


    @staticmethod
    def get_assigned(): # assigned to a table, don't care current status
        today = pd.Timestamp.now().floor('D')
        reservations_today = Reservation.objects.filter(time_reserved__gte=today)

        assigned = []
        for reservation in reservations_today:
            if reservation.tables:
                assigned.append(reservation)

        return assigned


class ReservationTable(models.Model):
    reservation = models.ForeignKey(to=Reservation, on_delete=models.CASCADE)
    table = models.ForeignKey(to=Table, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.reservation}, table {self.table.table_name}"


    @staticmethod
    def get_tables(reservation:Reservation=None, reservation_id:int=None)->list:
        """
        Get a list of tables assigned to a reservation. The list is empty if the given reservation hasn't been assigned
        to any table
        :param reservation:
        :param reservation_id:
        :return:
        """
        if not reservation_id and not reservation:
            raise TypeError("Must input at least a Reservation object or an ID")

        if reservation_id: # can raise a type error if the id is wrong
            reservation = Reservation.objects.get(id=reservation_id)

        try:
            values = ReservationTable.objects.filter(reservation=reservation).values_list('table')
            return [Table.objects.get(id=field[0]) for field in values]
        except ReservationTable.DoesNotExist:
            return []

reservation/views.py
import traceback

import pandas as pd
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponseRedirect, HttpResponse, QueryDict, JsonResponse
from django.urls import reverse
from django.views import generic

from reservation.models import Table, Reservation, ReservationTable


class _Cell:
    def __init__(self, content, color):
        self.content = content
        self.color = color

    def __str__(self):
        return str(self.content)


class ReservationView(generic.TemplateView):
    template_name = 'internal/reservation.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['today'] = pd.Timestamp.now().strftime("%Y-%m-%d")
        context['reservations'] = {
            'unassigned' : Reservation.get_unassigned(),
            'waiting' : Reservation.get_waiting(),
            'on_going' : Reservation.get_on_going(),
            'all' : Reservation.objects.all().filter(time_reserved__gte=pd.Timestamp.now().floor('D'))
        }
        context['tables'] = _get_reservation_table()

        return context


    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("home:home"))

        return super().get(request, *args, **kwargs)


    @staticmethod
    def post(request:WSGIRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("home:home"))

        try:
            match request.POST['type']:
                case 'assign':
                    ReservationView.assign(request.POST)
                case 'reservation':
                    ReservationView.reserve(request.POST)
                case 'confirm':
                    ReservationView.confirm(request.POST)
                case 'finished':
                    ReservationView.finish(request.POST)
                case 'delete':
                    ReservationView.delete(request.POST)
                case _:
                    pass
        except Exception as e:
            traceback.print_exception(e)

        return HttpResponseRedirect(reverse("reservation:home"))


    @staticmethod
    def reserve(payload:QueryDict):
        time_reserved = pd.Timestamp(f"{payload['date']} {payload['time_slot']}")

        phone = payload['phone'] or None if ("phone" in payload.keys()) else None
        # TODO: TABLE_ID
        reservation = Reservation(customer_name=payload['name'],
                                  customer_phone=phone,
                                  seat_count=payload['seat_count'],
                                  time_reserved=time_reserved)
        reservation.save()


    @staticmethod
    def assign(payload:QueryDict):
        reservation = Reservation.objects.get(id=payload['reservation'])

        for key, value in payload.items():
            if value == 'on':
                table = Table.objects.get(id=key)
                ReservationTable.objects.get_or_create(table=table, reservation=reservation)


    @staticmethod
    def confirm(payload:QueryDict):
        reservation = Reservation.objects.get(id=payload['reservation'])
        reservation.time_start = reservation.time_reserved

        reservation.save()


    @staticmethod
    def finish(payload:QueryDict):
        time_end = pd.Timestamp(f"{payload['time_slot']}")
        reservation = Reservation.objects.get(id=payload['reservation'])
        reservation.time_end = time_end

        reservation.save()


    @staticmethod
    def delete(payload:QueryDict):
        for key in payload.keys():
            if payload[key] == 'on':
                reservation = Reservation.objects.get(id=key)
                reservation.delete()


def _get_cell_content(r:Reservation)->_Cell:

    if r.time_start is None: # waiting, hasn't checked in
        return _Cell(r.customer_name, "darkorange")
    elif r.time_end is None: # ongoing, hasn't done
        return _Cell(r.customer_name, "red")
    elif r.time_end is not None:
        return _Cell(r.customer_name, "darkblue")

    return _Cell("Fehler", "red")


def get_time_opening():
    time_all = pd.date_range(start="12:00", end="20:30", freq='30min')

    weekday = pd.Timestamp.now().floor('D').weekday()

    SAT, SUN = 5, 6
    if weekday in [SAT, SUN]: # weekend no pause
        time_pause = pd.DatetimeIndex([])
    else:
        time_pause = pd.date_range(start="15:00", end="17:00", freq='30min', inclusive="left")

    return time_all.difference(time_pause)


def _get_reservation_table()->pd.DataFrame:
    time_opening = get_time_opening()

    table_ids = [table for table in Table.objects.all()]
    df = pd.DataFrame(index=table_ids, columns=time_opening)

    for reservation in Reservation.get_assigned():
        tables = reservation.tables
        # table_id = reservation.table

        if reservation.time_end is None:
            allocated_time = pd.date_range(start=reservation.time_reserved,
                                           end=reservation.time_reserved + pd.Timedelta(hours=2),
                                           freq='30min', inclusive='left') \
                                .tz_localize(None)
        else:
            allocated_time = pd.date_range(start=reservation.time_start,
                                           end=reservation.time_end,
                                           freq='30min')

        time = time_opening.intersection(allocated_time)

        cell_content = _get_cell_content(reservation)

        for table in tables:
            df.loc[table, time] = df.loc[table, time].fillna(value=cell_content)

    df = df.fillna(value=_Cell(False, "green"))

    df.columns = df.columns.strftime("%H:%M")

    return df


def _get_available_tables(reservation_id)->dict:
    """
    Get the list of available tables for this unassigned reservation
    :param reservation_id:
    :return:
    """

    reservation = Reservation.objects.get(id=reservation_id)
    free_tables = Table.get_free_at(reservation.time_reserved)

    to_json = lambda table: {
        "id": table.id,
        "seat_count": table.seat_count,
        "table_name": table.table_name,
    }

    big_tables = []
    small_tables = []

    for table in free_tables:
        if table.seat_count > 3:
            big_tables.append(to_json(table))
        else:
            small_tables.append(to_json(table))

    return {
        'big' : big_tables,
        'small' : small_tables,
    }


def ajax_reservation(request: WSGIRequest)->HttpResponse:
    """
    Register a new reservation from an ajax request from the external pages
    :param request: A WSGIRequest from an external page
    :return: 200 or 400 HTTP response
    """

    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        if request.method == 'POST':
            try:
                ReservationView.reserve(request.POST)
                return HttpResponse(status=200)
            except Exception as e:
                traceback.print_exception(e)

                return HttpResponse(status=400)

    return HttpResponse(status=405)


def ajax_get_available_tables(request: WSGIRequest)->HttpResponse:
    """
    Given a reservation, return the available tables for it
    :param request: A WSGIRequest from the internal reservation page
    :return: A json object containing the available tables if legit request, otherwise redirect
    """

    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.user.is_authenticated:
            if request.method == 'GET':
                return JsonResponse(_get_available_tables(request.GET['reservation_id']))
            else:
                return HttpResponseRedirect("reservation:home", status=405)
        else:
            return HttpResponseRedirect("home:home", status=401)

    return HttpResponseRedirect("home:home", status=400)

templates/internal/reservation/forms/assign_table.html
<form method="post" style="width: 100%;">
    {% csrf_token %}
    <fieldset style="display: inline-block; width: 80%">
        <legend>Tischen zuordnen</legend>

        {% include 'internal/reservation/forms/select_reservation.html' with reservations=reservations id='select_reservation_assign' %}

        <div style="display: flex">
            <fieldset style="width: 50%" id="fs_small_tables">
                <legend>Klein</legend>
                <div class="scrollable_div" id="div_small_tables"></div>
            </fieldset>

            <fieldset style="width: 50%" id="fs_big_tables">
                <legend>Groß</legend>
                <div class="scrollable_div" id="div_big_tables"></div>
            </fieldset>
        </div>

        <br>

        <input type="submit" value="Speichern" style="font-weight: bold">
        <input type="hidden" name="type" value="assign">
    </fieldset>

    <script>
        $('#select_reservation_assign').change(() => {
            let select = $('#select_reservation_assign');
            let div_small_tables = $("#div_small_tables");
            let div_big_tables = $("#div_big_tables");

            // reset to blank
            div_small_tables.empty();
            div_big_tables.empty();

            let reservation_id = select.val();
            if (reservation_id)
                $.ajax({
                    url : "{% url 'reservation:ajax_get_available_tables' %}",
                    type : "GET",
                    data : {
                        "reservation_id" : select.val()
                    },
                    success : (response) => {
                        let big_tables = response['big'];
                        let small_tables = response['small'];


                        for (let table of small_tables) {
                            let html = `<input type="checkbox" style="margin: 1px;" name="${table['id']}">` +
                                       `<label style="font-size: 80%;">T${table['table_name']} (${table['seat_count']}x)</label>` +
                                       `<br>`;

                            div_small_tables.append(html);
                        }

                        for (let table of big_tables) {
                            let html = `<input type="checkbox" style="margin: 1px;" name="${table['id']}">` +
                                       `<label style="font-size: 80%;">T${table['table_name']} (${table['seat_count']}x)</label>` +
                                       `<br>`;

                            div_big_tables.append(html);
                        }

                    },
                    error: (err) => {
                        console.log(err);
                    }
                })
        });
    </script>
</form>

templates/internal/reservation/forms/delete_reservation.html
<form method="post" style="width: 100%;">
    {% csrf_token %}
    <fieldset style="display: inline-block; width: 70%;">
        <legend>Reservierung löschen</legend>

        <div class="scrollable_div">
            {% if reservations %}

                {% for reservation in reservations %}
                    <input type="checkbox" style="margin: 1px" name="{{ reservation.id }}">
                    <label style="font-size: 80%;">{{ reservation }}</label>
                    <br>
                {% endfor %}
            {% else %}
                Keine austehende Reservierungen
            {% endif %}
        </div>

        <br>

        <input type="submit" value="Löschen" style="font-weight: bold">
        <input type="hidden" name="type" value="delete">

    </fieldset>
</form>

templates/internal/reservation/forms/manual_reservation.html
<form method="post">
    {% csrf_token %}

    <fieldset style="display: inline-block; width: 70%">
        <legend>Manuelle Reservierung</legend>

        <label>Erforderlich:</label><br>
            <input name="name" type="text" placeholder="Name" required>
            <br>

            <input type="date" name="date" min="{{ today }}" value="{{ today }}" style="margin-top: 1px" required>
            <select name="time_slot" style="margin-top: 1px" required>

                <option value="">Zeitslot</option>
                {% for time_slot in tables.columns %}
                    <option value="{{ time_slot }}">{{ time_slot }}</option>
                {% endfor %}
            </select>

            <br>
            <input name="seat_count" type="number" placeholder="Sitzenanzahl" style="margin-top: 1px" required>

        <br>

        <label>Optional:</label><br>
        <input name="phone" type="number" inputmode="numeric" placeholder="Phone">

{#        {% include 'internal/reservation/forms/select_table.html' with required=0 %}#}

        <br><br>

        <input type="submit" value="Speichern" style="font-weight: bold">
        <input type="hidden" name="type" value="reservation">
    </fieldset>
</form>

templates/internal/reservation/forms/select_reservation.html
<select name="reservation" style="width: 70%" required
{% if id %}
    id = {{ id }}
{% endif %}
>
    <option value="">Reservierung</option>
    {% for reservation in reservations %}
        <option value="{{ reservation.id }}">{{ reservation }}</option>
    {% endfor %}
</select>

templates/internal/reservation/forms/select_table.html
<select name="table" style="width: 25%"
{% if required %}
    required
{% endif %}
>
    <option value="">Tisch</option>
    {% for row in tables.iterrows %}
        <option value="{{ row.0.id }}">{{ row.0 }}</option>
    {% endfor %}
</select>

templates/internal/reservation/forms/set_finished.html
<form method="post">
    {% csrf_token %}
    <fieldset style="display: inline-block; width: 80%">
        <legend>Kunden fertig sind</legend>

        {% include 'internal/reservation/forms/select_reservation.html' with reservations=reservations %}

        <select name="time_slot" style="width: 27%;" required>

            <option value="">Fertig um</option>
            {% for time_slot in time_slots %}
                <option value="{{ time_slot }}">{{ time_slot }}</option>
            {% endfor %}
        </select>

        <br><br>

        <input type="submit" value="Bestätigen" style="font-weight: bold">
        <input type="hidden" name="type" value="finished">

    </fieldset>
</form>

templates/internal/reservation/forms/set_on_going.html
<form method="post">
    {% csrf_token %}
    <fieldset style="display: inline-block; width: 80%">
        <legend>Kunden kamen an</legend>

        {% include 'internal/reservation/forms/select_reservation.html' with reservations=reservations %}

        <br><br>

        <input type="submit" value="Bestätigen" style="font-weight: bold">
        <input type="hidden" name="type" value="confirm">

    </fieldset>
</form>