auth/urls.py
from django.urls import path

from auth.views import LoginView, ProfileView, SignUpView, PasswordChangeView, EmailChangeView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView

from menu.views import MenuEditView

app_name = 'auth'
urlpatterns = [
    path('',
         LoginView.as_view(),
         name='login'),

    path('logout/',
         LogoutView.as_view(template_name="internal/auth/logged_out.html"),
         name='logout'),

    path('password_change/',
         PasswordChangeView.as_view(),
         name="password_change"),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name="internal/auth/password_change_done.html"),
         name="password_change_done"),


    path('signup/', SignUpView.as_view(), name='sign_up'),
    path('management/', ProfileView.as_view(), name='logged_in'),


    path('edit_menu/', MenuEditView.as_view(), name='edit_menu'),
    path('change_email', EmailChangeView.as_view(), name='change_email')
]

home/urls.py
from django.urls import path

from home.views import HomeView, ContactView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', ContactView.as_view(), name='contact')
]

menu/urls.py
from django.urls import path

from menu.views import MenuView

app_name = 'menu'
urlpatterns = [
    path('', MenuView.as_view(), name='home'),
]

reservation/urls.py
from django.urls import path

from reservation.views import ReservationView, ajax_reservation, ajax_get_available_tables

app_name = 'reservation'
urlpatterns = [
    path('', ReservationView.as_view(), name='home'),
    path('reserve', ajax_reservation, name="ajax_reservation"),
    path('get-table', ajax_get_available_tables, name='ajax_get_available_tables')
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('menu/', include("menu.urls")),
    path('reservierung/', include("reservation.urls")),
    path('konto/', include("auth.urls"))
]

templates/external/base/book_table.html
{% load static %}

<section id="book-table">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="heading">
                    <h2>Reservieren Ihren Tisch hier</h2>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-2 col-sm-12">
                <div class="left-image">
                    <img src="{% static 'img/book_left_image.jpg' %}" alt="">
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div class="right-info">
                    <h4>Reservierung</h4>
                    {% include 'external/base/book_table_form.html' with timeslots=timeslots %}
                </div>
            </div>
        </div>
    </div>
</section>

templates/external/base/book_table_form.html
<div>
    <div class="row">
        <div class="col-md-6">
            <fieldset>
                <input type="date" style="margin-top: 0; margin-bottom: 0;" id="input_date" name="date" required>
            </fieldset>

            <script>
                let today = new Date();
                let Y = today.getFullYear();
                let M = String(today.getMonth() + 1).padStart(2, '0');
                let D = String(today.getDate()).padStart(2, '0');

                let strftime = Y + "-" + M + "-" + D;

                document.getElementById("input_date").setAttribute("min", strftime);
                document.getElementById("input_date").setAttribute("value", strftime);
            </script>
        </div>
        <div class="col-md-6">
            <fieldset>
                <select required name='time_slot' id="input_time">
                    <option value="">Zeitpunkt</option>
                    {% for timeslot in timeslots %}
                        <option value="{{ timeslot }}">{{ timeslot }}</option>
                    {% endfor %}
                </select>
            </fieldset>
        </div>
        <div class="col-md-6">
            <fieldset>
                <input name="name" type="text" class="form-control" id="input_name" placeholder="Name" required="">
            </fieldset>
        </div>
        <div class="col-md-6">
            <fieldset>
                <input name="phone" type="text" class="form-control" id="input_phone" placeholder="Telefon (optional)">
            </fieldset>
        </div>
        <div class="col-md-6">
            <fieldset>
                <input name="seat_count" type="number" class="form-control" style="margin-top: 0; margin-bottom: 0;" id="input_seat_count" placeholder="Sitzplatzanzahl" required>
            </fieldset>
        </div>
        <div class="col-md-6">
            <fieldset>
                <button type="submit" id="form-submit" class="btn" onclick="btn_book()">Reservieren</button>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <p id="p_reservation_noti" style="color: black" hidden></p>
    </div>
</div>

<script>
    function btn_book() {
        const is_empty = (str) => {
            return str.trim().length === 0
        }

        let time_slot = $("#input_time").val();
        let name = $("#input_name").val();
        let seat_count = $("#input_seat_count").val();

        let noti = $("#p_reservation_noti");

        let is_invalid = is_empty(time_slot) || is_empty(name) || is_empty(seat_count);

        if (is_empty(time_slot)) {
            noti.text("Bitte geben Sie die Zeitpunkt ein");
        } else if (is_empty(name)) {
            noti.text("Bitte geben Sie Ihre Name ein");
        } else if (is_empty(seat_count)) {
            noti.text("Bitte geben Sie die Sitzplatzanzahl ein");
        }
        noti.attr("hidden", false);

        if (is_invalid) {
            noti.css("color", "red");

            return;
        }


        let payload = {
            'csrfmiddlewaretoken' : '{{ csrf_token }}',
            'name' : name,
            'date' : $("#input_date").val(),
            'time_slot' : time_slot,
            'seat_count' : seat_count,
            'phone' : $("#input_phone").val(),
        }

        noti.text("")

        $.ajax({
            url : "{% url 'reservation:ajax_reservation' %}",
            type : "POST",
            data : payload,
            success : (response) => {
                noti.css("color", "green");
                noti.text("Reservierungsanfrage gesendet!");

                // reset back to normal
                $("#input_time").val("");
                $("#input_name").val("");
                $("#input_phone").val("");
                $("#input_seat_count").val("");
            },
            error: (err) => {
                console.log(err);
                noti.css("color", "red");
                noti.text("Es ist ein Fehler aufgetreten, bitte versuchen Sie später erneut.")
            }
        })
    }
</script>

templates/external/base/featured.html
{% load static %}

<section class="featured-food">
    <div class="container">
        <div class="row">
            <div class="heading">
                <h2>Weekly Featured Food</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="food-item">
                    <h2>Breakfast</h2>
                    <img src="{% static 'img/breakfast_item.jpg' %}" alt="">
                    <div class="price">$4.50</div>
                    <div class="text-content">
                        <h4>Kale Chips Art Party</h4>
                        <p>Dreamcatcher squid ennui cliche chicharros nes echo  small batch jean shorts hexagon street art knausgaard wolf...</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="food-item">
                    <h2>Lunch</h2>
                    <img src="{% static 'img/lunch_item.jpg' %}" alt="">
                    <div class="price">$7.50</div>
                    <div class="text-content">
                        <h4>Taiyaki Gastro Tousled</h4>
                        <p>Dreamcatcher squid ennui cliche chicharros nes echo  small batch jean shorts hexagon street art knausgaard wolf...</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="food-item">
                    <h2>Dinner</h2>
                    <img src="{% static 'img/dinner_item.jpg' %}" alt="">
                    <div class="price">$12.50</div>
                    <div class="text-content">
                        <h4>Batch Squid Jean Shorts</h4>
                        <p>Dreamcatcher squid ennui cliche chicharros nes echo  small batch jean shorts hexagon street art knausgaard wolf...</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="food-item">
                    <h2>Dinner</h2>
                    <img src="{% static 'img/dinner_item.jpg' %}" alt="">
                    <div class="price">$12.50</div>
                    <div class="text-content">
                        <h4>Batch Squid Jean Shorts</h4>
                        <p>Dreamcatcher squid ennui cliche chicharros nes echo  small batch jean shorts hexagon street art knausgaard wolf...</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/external/base/food_item.html
{% load static %}

<div class="item col-md-12">
    <div class="food-item">
        <img src="{% static food_item.img %}" alt="">
        <div class="price">€{{ food_item.price }}</div>
        <div class="text-content">
            <h4>{{ food_item.name }}</h4>
            <p>{{ food_item.description }}</p>
        </div>
    </div>
</div>

templates/external/base/footer.html
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p>Goethestr. 31, 34119 Kassel</p>
            </div>
            <div class="col-md-4">
                <ul class="social-icons">
                    <li>
                        <a rel="nofollow" href="https://fb.com/">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </li>

{#                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>#}
{#                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>#}
{#                    <li><a href="#"><i class="fa fa-rss"></i></a></li>#}
{#                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>#}
                </ul>
            </div>
            <div class="col-md-4">
                <p>Tel: 0561-93711468</p>
            </div>
        </div>
    </div>
</footer>

templates/external/base/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!--
    Victory HTML CSS Template
    https://templatemo.com/tm-507-victory
    -->
    <title>{{title}}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/hero-slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Spectral:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}"/>


    <script src="{% static "js/vendor/modernizr-2.8.3-respond-1.4.2.min.js" %}"></script>
</head>

templates/external/base/header.html
<div class="header">
    <div class="container">
{#        <a href="#" class="navbar-brand scroll-top">Ginko Kassel</a>#}
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="navbar-header">
                <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!--/.navbar-header-->
            <div id="main-nav" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:home' %}">Home</a></li>
                    <li><a href="{% url 'menu:home' %}">Speisekarte</a></li>
                    <li><a href="{% url 'home:contact' %}">Kontakt</a></li>
                </ul>
            </div>
            <!--/.navbar-collapse-->
        </nav>
        <!--/.navbar-->
    </div>
    <!--/.container-->
</div>

templates/external/base/heading.html
<section class="page-heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{ title }}</h1>
            </div>
        </div>
    </div>
</section>