auth/urls.py
from django.urls import path

from auth.views import LoginView, ProfileView, SignUpView, PasswordChangeView, EmailChangeView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView

from menu.views import MenuEditView

app_name = 'auth'
urlpatterns = [
    path('',
         LoginView.as_view(),
         name='login'),

    path('logout/',
         LogoutView.as_view(template_name="internal/auth/logged_out.html"),
         name='logout'),

    path('password_change/',
         PasswordChangeView.as_view(),
         name="password_change"),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name="internal/auth/password_change_done.html"),
         name="password_change_done"),


    path('signup/', SignUpView.as_view(), name='sign_up'),
    path('management/', ProfileView.as_view(), name='logged_in'),


    path('edit_menu/', MenuEditView.as_view(), name='edit_menu'),
    path('change_email', EmailChangeView.as_view(), name='change_email')
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('menu/', include("menu.urls")),
    path('reservierung/', include("reservation.urls")),
    path('konto/', include("auth.urls"))
]

templates/internal/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="de_DE">
    <head>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
        <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}"/>

        <script
            src="https://code.jquery.com/jquery-3.6.1.min.js"
            integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
            crossorigin="anonymous">
        </script>

        <style>
            * {
                font-family: Arial, serif;
            }

            .scrollable_div {
                overflow-y: scroll;
                min-height: 50px;
                max-height: 80px;
                border-style: solid;
                border-width: 1px;
                border-color: lightgrey;
                text-align: left;
            }
        </style>

        <title>{% block title %}{% endblock %}</title>

        {% block head %}{% endblock %}

    </head>

    <body>
        <a href="{% url 'auth:logged_in' %}">Home</a>
        {% block content %}{% endblock %}
    </body>

</html>

templates/internal/base/table_head.html
<link type="text/css" rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.1/fc-4.2.1/datatables.min.js"></script>

<style>
    .table {
        border-collapse: collapse; /* Collapse borders */
        border: 1px solid #ddd; /* Add a grey border */
    }

    .table th, .table td {
        text-align: center;
    }

    .table tr {
        /* Add a bottom border to all table rows */
        border-bottom: 1px solid #ddd;
    }

    .table_header, .table tr:hover {
        /* Add a grey background color to the table header and on hover */
        background-color: #f1f1f1;
    }
</style>